apiVersion: v1
kind: Service
metadata:
  name: mutating-pebble-webhook-svc
  namespace: pebble-webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: mutating-pebble-webhook
