apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
 name: "mutating-pebble-webhook.pebble-webhook.svc"
webhooks:
 - name: "mutating-pebble-webhook.pebble-webhook.svc"
   namespaceSelector:
     matchExpressions:
       - key: skip-pebble-mount
         operator: NotIn
         values: ["true"]
   rules:
     - apiGroups: [""]
       apiVersions: ["v1"]
       operations: ["CREATE"]
       resources: ["pods"]
       scope: "*"
   sideEffects: None
   admissionReviewVersions: ["v1"]
   clientConfig:
     service:
       namespace: pebble-webhook
       name: mutating-pebble-webhook-svc
       path: /add-pebble-mount
       port: 443
     caBundle: LS0t...
